WIP: added Done Button and Feelings View
Added moods to store
Added new route for FeelingsView
Modifed navigation logic
Getting an error from vue-router:
	Uncaught (in promise) TypeError: api.now is not a function
Google says it's related to router 3 with vue 3, but this is
router 4, so it's something else?